### PR TITLE
Rely purely on Orbit for 3rd party dependencies

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-simrel/simrel.build/issues/438

### CODE REVIEW

**Comment by merks** [comment]
I ran the build locally and everything build fine with this change with only one test failure:

image

**Comment by merks** [comment]
@mknauer @ifurnadjiev 

Does someone need to approve to run a PR build ?

**Comment by mknauer** [comment]
ok to test

**Review by mknauer — APPROVED** [review]
Looks great to me, especially the removal of the additional "extra-dependencies" repository. I reviewed that, and indeed, is it not needed any more. Thanks!

**Comment by merks** [comment]
Yeah!  🥳

**Pull request merged**
