### PR TITLE
Add mode to make text-size-store session scoped

### PR DESCRIPTION
**Pull request by ceisserer**
This is a follow-up to https://github.com/eclipse-rap/org.eclipse.rap/pull/67

As requested I added two unit tests and removed the use of static fields to cache the property, as this led to issues when testing.

### CODE REVIEW

**Comment by mknauer** [comment]
ok to test

**Comment by ceisserer** [comment]
@ifurnadjiev could you please have a look, it would be great if this could land in RAP 3.28

**Comment by ifurnadjiev** [comment]
I have an updated local version of your previous change, but I will review the last version as soon aa possible.

**Comment by ifurnadjiev** [comment]
@ceisserer I'm still curios, did you find the reason why the text-size-determination is not working correctly? With this implementation we are trying to fix something, which is unclear why it's happening.

**Comment by ceisserer** [comment]
Hi Ivan,

one of the things I found breaking the app-wide text-size-cache is page-zoom, which has become much more common because of highdpi devices. I guess this is also the reason why we started seeing this problem more frequently in recent years until ~2021 when we applied this patch. I was also able to poision the cache by changing the font while the webapp was in use, but I guess this is not so common. On the other hand, a single user changing fonts using a font-override plugin during use (maybe for visual assistance) means if you are not lucky you have to restart your server.

I found a not-so-uncommon way to reproduce the problem with our internal apps:
- start app server
- login the first time with 100% zoom (probe is calculated with this resolution), change zoom drastically to 30%, navigate to a few other pages. this will poison the app-wide text-size-cache, because text-layout is done differently at 30% (still scaled, but maybe there are rounding errors in the text layout engines) and values are still cached at the 100% probe.
- use another browser instance, open the app again at 100% - first page is still fine (as text-size was determined by the other browser at 100% too)
- navigate to the pages which were visited by the other browser with 30% -> texts are mis-measured.

The main issue I see is the probe is only calculated when the webapp is initialized. later changes to the environment which might affect text-rendering are not detected and can lead to invalid values inside the cache.

I guess the really proper way to do caching would be to:
- layout on the server using the cached text-sizes
- re-measure every cached text-size on the client again (-> iff they match or are in a certain tolerance, no need for a re-layout roundtrip)
- in case they differ, re-layout using the just performed text-measurements

**Comment by ifurnadjiev** [comment]
Thank you for the explanation. But with this approach (use user session scoped TSD), it's still possible to have big differences if you change the zoom level after the TSD cache is filled. Load page with 100%, navigate to another one, change zoom to 30%, return back to the first one. I'm I correct?

**Comment by ifurnadjiev** [comment]
... one idea. What about if you "convert" the text dimensions to zoom 100% before sending to the server, and adjust the widget bound to the current zoom level of the browser when applied? Than on the server will will always have the text dimensions on zoom 100% (like it is now) and adjust the client only to the current zoom level. In all the recent browsers `window.devicePixelRatio` gives similar results.

**Comment by ifurnadjiev** [comment]
... what about cached value per zoom level. Currently, we are using this [method](https://github.com/eclipse-rap/org.eclipse.rap/blob/main/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/TextSizeStorageUtil.java#L53) to calculate the text key. We can add there also the zoom level on which this value is measured. Than, all the values will be zoom specific. What do you think?

**Comment by ceisserer** [comment]
maybe caching per zoom level would help. but then what about someone using assistive technologies who is overriding fonts right in between the session. or other irregularities that might occur between measuring the probe and masuring actual text fragments which will be cached. to guard against this, we could re-measure the probe at each request to see if the initial assumtion still holds, so the time-window would at least be as small as possible.

However my main concern when it comes to caching as-is would remain: a single client-system is able to poison the text cache (intentionally or unintentionally) in a way that "normal" users suffer and only an application restart can restore the "good" behaviour. Couldn't intentionally submitting fake measurements even allow an attacker to render an application unuseable?

**Comment by ifurnadjiev** [comment]
I did small refactoring in your code and pushed another PR; https://github.com/eclipse-rap/org.eclipse.rap/pull/166

**Comment by ifurnadjiev** [comment]
Closed in favor of https://github.com/eclipse-rap/org.eclipse.rap/pull/166

**Pull request closed without merging**
