### PR TITLE
Use Apache "commons-fileupload2" javax bundles

### PR DESCRIPTION
**Pull request by ifurnadjiev**

### CODE REVIEW

**Review by mknauer — APPROVED** [review]

**Comment by merks** [comment]
I noticed these additional bundles and I see these are not yet available at Maven Central.  I guess they will be at some point in the future such that they can be provided from Orbit?

**Comment by mknauer** [comment]
@merks Yes, making them available via Orbit would be my ultimate goal.

For now, we needed a quick solution during our own milestone development, even if it's just our own temporary p2 repository. In fact, they are already available from Maven Central in version 2.0.0-M2 [1], but as the name suggests, it's ‘only’ an M2 build, and I haven't seen any further work on the release versions yet.

[1] https://central.sonatype.com/search?q=fileupload2

**Comment by merks** [comment]
I see!  I was looking in the wrong place.  I see these here:

image

The M1/M2 suggest these are milestones, not releases...

I will investigate what's involved in getting them into Orbit, but given they are OSGi artifacts, that should be straightforward.   I wonder if eventually there will be RC* versions too, or just a final 2.0.0 eventually...

Thanks for the details!

**Comment by merks** [comment]
@mknauer 

The above are now available in Orbit and this updates the RAP runtime build to use them:

https://github.com/eclipse-rap/org.eclipse.rap/pull/202

**Comment by mknauer** [comment]
Wow, what a service! Thank you, Ed! :slightly_smiling_face:

**Pull request merged**
